### ISSUE TITLE
Include node-toggl-api with hardcoded configs

### ISSUE THREAD

**Issue by shmygol** [trilliput/google-apps-toggl-reports#3]
1. Add [node-toggl-api](https://github.com/7eggs/node-toggl-api) as an npm requirement
2. set required configs in an appropriate config file (eventually toggl token will be set by user through UI form)
3. implement [toggl.com](https://toggl.com) authentication
4. Tests

**Comment by shmygol** [comment]
It's not possible to use node-toggle-api in Google Scripts. The functionality will be implemented in scope of the isseu #10.

**Comment by trilliput** [comment]
It's not possible to use node-toggle-api in Google Scripts. The functionality will be implemented in scope of the isseu #10.
